Layout/ParameterAlignment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Layout/LineLength:
  Enabled: false

# Style/BracesAroundHashParameters:
#   Enabled: false

Style/GuardClause:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Rails/Date:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Rails/InverseOf:
  Enabled: false

# 個人的にはこれは true にしてもいいかと
Rails/HasManyOrHasOneDependent:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

# ヘルパーの中にインスタンス変数を使うなということだが、いったん無効にする
Rails/HelperInstanceVariable:
  Enabled: false

AsciiComments:
  Enabled: false
