default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV['RAILS_MAX_THREADS'] || Rails.application.credentials[:rails_max_threads] || 5 %>
  host:     <%= ENV['POSTGRES_HOST'] || Rails.application.credentials[:postgres_host] || 'localhost' %>
  port:     <%= ENV['POSTGRES_PORT'] || Rails.application.credentials[:postgres_port] || 5432 %>
  username: <%= ENV['POSTGRES_USERNAME'] || Rails.application.credentials[:postgres_username] || 'tweet_storage' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || Rails.application.credentials[:postgres_password] || 'tweet_storage' %>

production:
  <<: *default
  database: tweet_storage_production
  host: <%= ENV['POSTGRES_HOST_PRODUCTION'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT_PRODUCTION'] || 5432 %>
  username: <%= ENV['POSTGRES_USERNAME_PRODUCTION'] || 'tweet_storage' %>
  password: <%= ENV['POSTGRES_PASSWORD_PRODUCTION'] || 'tweet_storage' %>

development:
  <<: *default
  database: tweet_storage_development
  host: <%= ENV['POSTGRES_HOST_DEVELOPMENT'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT_DEVELOPMENT'] || 5432 %>
  username: <%= ENV['POSTGRES_USERNAME_DEVELOPMENT'] || 'tweet_storage' %>
  password: <%= ENV['POSTGRES_PASSWORD_DEVELOPMENT'] || 'tweet_storage' %>

test:
  <<: *default
  database: tweet_storage_test
  # host: <%= ENV['POSTGRES_HOST_TEST'] || 'localhost' %>
  # port: <%= ENV['POSTGRES_PORT_TEST'] || 5432 %>
  # username: <%= ENV['POSTGRES_USERNAME_TEST'] || 'tweet_storage' %>
  # password: <%= ENV['POSTGRES_PASSWORD_TEST'] || 'tweet_storage' %>
